# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 13:17
from __future__ import unicode_literals

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.CharField(default=core.models.get_hash_id, editable=False, max_length=16, primary_key=True, serialize=False, validators=[core.validators.validate_hash_id])),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=core.models.get_hash_id, editable=False, max_length=16, primary_key=True, serialize=False, validators=[core.validators.validate_hash_id])),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email', 'first_name', 'last_name')]),
        ),
    ]
