# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 03:08
# flake8: noqa
from __future__ import unicode_literals

import core.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(default=core.models.get_hash_id, editable=False, max_length=16, primary_key=True, serialize=False, validators=[core.validators.validate_hash_id])),
                ('created', models.DateTimeField(auto_now_add=True, help_text='contract creation date and time')),
                ('start_date', models.DateField(help_text='starting date for the contract')),
                ('end_date', models.DateField(help_text='ending date for the contract')),
                ('rent', models.DecimalField(decimal_places=2, help_text='monthly value in pounds that should be payed by tenant', max_digits=10)),
                ('property', models.ForeignKey(help_text='property associated with the contract', on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
                ('tenant', models.ForeignKey(help_text='tenant associated with the contract', on_delete=django.db.models.deletion.CASCADE, to='accounts.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
